name: fireplugstats
region: nyc
services:
  - name: web
    github:
      repo: jamesvandyke/fireplugstats
      branch: main
      deploy_on_push: true
    environment_slug: node-js
    run_command: HOST=0.0.0.0 PORT=8080 npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /
